In [1]:
import numpy as np

In [2]:
data = np.linspace(1,2,10)
data

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [5]:
dt2  = np.linspace(1,2,20)
dt2

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [6]:
type(dt2)

numpy.ndarray

In [13]:
dt2[::-1]

array([2.        , 1.94736842, 1.89473684, 1.84210526, 1.78947368,
       1.73684211, 1.68421053, 1.63157895, 1.57894737, 1.52631579,
       1.47368421, 1.42105263, 1.36842105, 1.31578947, 1.26315789,
       1.21052632, 1.15789474, 1.10526316, 1.05263158, 1.        ])

In [15]:
dt2[1:10:1]

array([1.05263158, 1.10526316, 1.15789474, 1.21052632, 1.26315789,
       1.31578947, 1.36842105, 1.42105263, 1.47368421])